name: Rust-Cargo Build

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      version:
        description: Terracotta Version
        type: string

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always
  name: terracotta
  RUST_BACKTRACE: full
  TERRACOTTA_U_S: ${{ secrets.TERRACOTTA_U_S }}

defaults:
  run:
    shell: bash

jobs:
  build-windows:
    strategy:
      fail-fast: false
      matrix:
        include:
          - runs-on: windows-latest
            os: windows
            arch: x86_64
            target: x86_64-pc-windows-msvc
          - runs-on: windows-11-arm
            os: windows
            arch: arm64
            target: aarch64-pc-windows-msvc
    runs-on: ${{ matrix.runs-on }}
    name: Build (${{ matrix.target }})
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install GitHub Artifact Client
        uses: lhotari/gh-actions-artifact-client@v2
      - name: Compute Version
        run: |
          if [ -z "${{ github.event.inputs.version }}" ]; then
            echo "TERRACOTTA_VERSION=${GITHUB_SHA::7}" >> $GITHUB_ENV
          else
            echo "TERRACOTTA_VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV
          fi
      - name: Build
        run: |
          rustup target add --toolchain nightly "${{ matrix.target }}"
          rustup component add rust-src --toolchain "nightly-$(rustc --print host-tuple)"
          cargo +nightly build --release --bin terracotta --target "${{ matrix.target }}" \
            -Z build-std=core,std,alloc,proc_macro,panic_abort \
            -Z build-std-features=default,optimize_for_size
        env:
          RUSTFLAGS: -Zunstable-options -Cpanic=immediate-abort
      - name: Upload Artifact
        run: |
          source="terracotta-${TERRACOTTA_VERSION}-${{ matrix.os }}-${{ matrix.arch }}.exe"
          cp "target/${{ matrix.target }}/release/terracotta.exe" "$source"
          7z a "$source.zip" "$source"
          cat "$source.zip" | gh-actions-artifact-client.js upload -r 90 "$source"
  build-unix:
    strategy:
      fail-fast: false
      matrix:
        include:
          - { os: android, arch: arm64v8a,    target: aarch64-linux-android }
    runs-on: ${{ matrix.runs-on || 'ubuntu-24.04' }}
    name: Build (${{ matrix.target }})
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install GitHub Artifact Client
        uses: lhotari/gh-actions-artifact-client@v2
      - name: Compute Version
        run: |
          if [ -z "${{ github.event.inputs.version }}" ]; then
            echo "TERRACOTTA_VERSION=${GITHUB_SHA::7}" >> $GITHUB_ENV
          else
            echo "TERRACOTTA_VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV
          fi
      - name: Install cargo-ndk and protobuf-compiler (Android)
        if: ${{ matrix.os == 'android' }}
        run: |
          sudo apt update
          sudo apt install --yes --no-install-recommends protobuf-compiler libprotobuf-dev
          cargo install cargo-ndk --force
      - name: Build (Android)
        if: ${{ matrix.os == 'android' }}
        run: |
          export PATH="$PATH:$ANDROID_NDK_LATEST_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin"
          export NDK_HOME="$ANDROID_NDK_LATEST_HOME"
          
          rustup target add --toolchain nightly "${{ matrix.target }}"
          rustup component add rust-src --toolchain "nightly-$(rustc --print host-tuple)"
          cargo +nightly ndk build --release --lib --target "${{ matrix.target }}" \
            -Z build-std=core,std,alloc,proc_macro,panic_abort \
            -Z build-std-features=default,optimize_for_size
        env:
          RUSTFLAGS: -Zunstable-options -Cpanic=unwind
      - name: Upload Artifact
        run: |
          source="terracotta-${TERRACOTTA_VERSION}-${{ matrix.os }}-${{ matrix.arch }}.so"
          cp "target/${{ matrix.target }}/release/libterracotta.so" "$source"
          
          chmod 755 "$source"
          tar -cf "$source.tar" "$source"
          zip -q - "$source.tar" | gh-actions-artifact-client.js upload -r 90 "$source.tar"
